
package webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LivreWS", targetNamespace = "http://webservices/", wsdlLocation = "http://localhost:8686/LivreWS?wsdl")
public class LivreWS
    extends Service
{

    private final static URL LIVREWS_WSDL_LOCATION;
    private final static WebServiceException LIVREWS_EXCEPTION;
    private final static QName LIVREWS_QNAME = new QName("http://webservices/", "LivreWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8686/LivreWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LIVREWS_WSDL_LOCATION = url;
        LIVREWS_EXCEPTION = e;
    }

    public LivreWS() {
        super(__getWsdlLocation(), LIVREWS_QNAME);
    }

    public LivreWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), LIVREWS_QNAME, features);
    }

    public LivreWS(URL wsdlLocation) {
        super(wsdlLocation, LIVREWS_QNAME);
    }

    public LivreWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LIVREWS_QNAME, features);
    }

    public LivreWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LivreWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LivreService
     */
    @WebEndpoint(name = "LivreServicePort")
    public LivreService getLivreServicePort() {
        return super.getPort(new QName("http://webservices/", "LivreServicePort"), LivreService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LivreService
     */
    @WebEndpoint(name = "LivreServicePort")
    public LivreService getLivreServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices/", "LivreServicePort"), LivreService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LIVREWS_EXCEPTION!= null) {
            throw LIVREWS_EXCEPTION;
        }
        return LIVREWS_WSDL_LOCATION;
    }

}
